Repository Nahid1911/space-travelers-proj-react, pull requests merged in 2023-06, with the labels that each got.

#26 Feature/setup
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .stylelintrc.json
  README.md
  assets/logo.svg
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
Labels: Setup

#27 Feature/navigation
  package-lock.json
  package.json
  src/App.js
  src/components/Dragon/Dragon.js
  src/components/Mission/Mission.js
  src/components/MyProfile/MyProfile.js
  src/components/NavBar.js
  src/components/NavBar.module.css
  src/components/Rocket/Rocket.js
  src/components/assets/logo.svg
  src/components/assets/planet_bigger.png
  src/index.js
Labels: enhancement

#28 Connect Redux store with the app
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/logo.svg
  src/index.js
  src/redux/Store.js
  src/redux/dragonsSlice/dragonsSlice.js
  src/redux/missionsSlice/missionsSlice.js
  src/redux/rocketsSlice/rocketsSlice.js
Labels: enhancement

#29 Create basic structure of missions
  src/components/Mission/Mission.js
Labels: enhancement

#30 Create basic structure of Dragons Feature
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/Dragon/Dragon.css
  src/components/Dragon/Dragon.js
  src/index.css
Labels: enhancement

#32 Feature/fetch missions
  src/components/Mission/Mission.js
  src/components/NavBar.js
  src/redux/Store.js
  src/redux/missionsSlice/missionsSlice.js
Labels: enhancement

#34 Fetch Data from endpoint to redux store
  package-lock.json
  package.json
  src/App.js
  src/components/Dragon/Dragon.js
  src/components/NavBar.js
  src/redux/Store.js
  src/redux/dragonsSlice/dragonsSlice.js
Labels: enhancement

#39 Fetch rockets data
  src/components/Rocket/Rockets.js
  src/redux/Store.js
  src/redux/rocketsSlice/rocketsSlice.js
Labels: enhancement

#40 Implement Dragon Reserve Button
  src/components/Dragon/Dragon.css
  src/components/Dragon/DragonItem.js
  src/redux/dragonsSlice/dragonsSlice.js
Labels: Partners Review

#37 Feature/badge mission
  src/App.css
  src/App.js
  src/components/Mission/Mission.js
  src/redux/missionsSlice/missionsSlice.js
Labels: enhancement

#41 Add display data
  src/App.css
  src/components/Rocket/Rocket.css
  src/components/Rocket/Rocket.js
  src/components/Rocket/RocketItem.js
  src/components/Rocket/Rockets.js
  src/redux/Store.js
  src/redux/rocketsSlice/rocketsSlice.js
Labels: enhancement

#43 Feature/joined missions my profile
  src/components/MyProfile/MyProfile.js
  src/components/MyProfile/MyProfile.module.css
  src/components/NavBar.module.css
  src/index.css
  src/index.js
  src/redux/missionsSlice/missionsSlice.js
Labels: enhancement

#45 Add reserve rocket
  src/components/Rocket/Rocket.css
  src/components/Rocket/Rockets.js
  src/redux/rocketsSlice/rocketsSlice.js
Labels: enhancement

#47 Test Navigation bar components
  package-lock.json
  package.json
  src/test/NavBar.test.js
  src/test/__snapshots__/NavBar.test.js.snap
Labels: Testing

#46 Add rocket booking cancelation actions
  src/redux/rocketsSlice/rocketsSlice.js
Labels: enhancement

#52 Link user profile with dragon booking
  src/components/Dragon/Dragon.js
  src/components/Dragon/DragonItem.js
  src/components/MyProfile/MyProfile.js
  src/redux/dragonsSlice/dragonsSlice.js
  src/redux/rocketsSlice/rocketsSlice.js
Labels: Partners Review

#54 Feature/readme file
  MIT.md
  README.md
  src/components/MyProfile/MyProfile.js
Labels: documentation

#57 Feature/test dragon
  src/components/Rocket/Rocket.css
  src/redux/dragonsSlice/dragonsSlice.js
  src/redux/rocketsSlice/rocketsSlice.js
  src/test/FetchDragon.test.js
  src/test/cancelDragonReservation.test.js
  src/test/reserveDragon.test.js
Labels: Testing
